/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package itson.biblioteca.musical.gui;

import itson.biblioteca.musical.modelo.Usuario;
import itson.biblioteca.musical.persistencia.FavoritoDAO;
import itson.biblioteca.musical.persistencia.UsuarioDAO;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Felix_isq
 */
public class GenerosNoDeseadosForm extends javax.swing.JFrame {

    private DefaultListModel<String> modeloLista;
    private Usuario usuario;

    /**
     * Creates new form GenerosNoDeseadosForm
     */
    public GenerosNoDeseadosForm() {
        initComponents();
    }

    public GenerosNoDeseadosForm(Usuario usuario) {
        this.usuario = usuario;
        initComponents();

        // ← Aquí agregas la carga de la lista:
        modeloLista = new DefaultListModel<>();
        for (String genero : usuario.getGenerosNoDeseados()) {
            modeloLista.addElement(genero);
        }
        listaGeneros.setModel(modeloLista);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPaneGeneros = new javax.swing.JScrollPane();
        listaGeneros = new javax.swing.JList<>();
        txtNuevoGenero = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        scrollPaneGeneros.setName("scrollPaneGeneros"); // NOI18N

        listaGeneros.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaGeneros.setName("listaGeneros"); // NOI18N
        scrollPaneGeneros.setViewportView(listaGeneros);

        txtNuevoGenero.setName("txtNuevoGenero"); // NOI18N

        btnAgregar.setText("Agregar");
        btnAgregar.setName("btnAgregar"); // NOI18N
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.setName("btnEliminar"); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAgregar)
                        .addGap(73, 73, 73)
                        .addComponent(btnEliminar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scrollPaneGeneros, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNuevoGenero, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                        .addGap(12, 12, 12))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(scrollPaneGeneros, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(txtNuevoGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        String nuevo = txtNuevoGenero.getText().trim().toLowerCase();
        if (nuevo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingresa un género válido.");
            return;
        }

        if (modeloLista.contains(nuevo)) {
            JOptionPane.showMessageDialog(this, "Este género ya está en la lista.");
            return;
        }

        modeloLista.addElement(nuevo);
        usuario.getGenerosNoDeseados().add(nuevo);
        new UsuarioDAO().actualizarGenerosNoDeseados(usuario.getCorreo(), usuario.getGenerosNoDeseados());

        JOptionPane.showMessageDialog(
                this,
                " El género '" + nuevo + "' fue agregado exitosamente.",
                "Género agregado",
                JOptionPane.INFORMATION_MESSAGE
        );

        int eliminados = new FavoritoDAO().eliminarFavoritosPorGenero(usuario.getCorreo(), nuevo);
        if (eliminados > 0) {
            JOptionPane.showMessageDialog(this, "Se eliminaron " + eliminados + " favoritos del género '" + nuevo + "'.");
        }

        txtNuevoGenero.setText("");


    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:

        String seleccionado = listaGeneros.getSelectedValue();
        if (seleccionado == null) {
            JOptionPane.showMessageDialog(this, "Selecciona un género para eliminar.");
            return;
        }

        modeloLista.removeElement(seleccionado);
        usuario.getGenerosNoDeseados().remove(seleccionado);
        new UsuarioDAO().actualizarGenerosNoDeseados(usuario.getCorreo(), usuario.getGenerosNoDeseados());

        JOptionPane.showMessageDialog(
                this,
                " El género '" + seleccionado + "' fue eliminado de tus restricciones.",
                "Género eliminado",
                JOptionPane.INFORMATION_MESSAGE
        );

    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenerosNoDeseadosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenerosNoDeseadosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenerosNoDeseadosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenerosNoDeseadosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenerosNoDeseadosForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JList<String> listaGeneros;
    private javax.swing.JScrollPane scrollPaneGeneros;
    private javax.swing.JTextField txtNuevoGenero;
    // End of variables declaration//GEN-END:variables
}
